---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ingress-nginx-kubebuilder-io-v1-ingress
  failurePolicy: Fail
  name: mingress.kb.io
  rules:
  - apiGroups:
    - ingress.nginx.kubebuilder.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ingress-nginx-kubebuilder-io-v1-ingress
  failurePolicy: Fail
  name: vingress.kb.io
  rules:
  - apiGroups:
    - ingress.nginx.kubebuilder.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  sideEffects: None
