# permissions for end users to edit ingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ingress-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ingress-nginx-kubebuilder
    app.kubernetes.io/part-of: ingress-nginx-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: ingress-editor-role
rules:
- apiGroups:
  - ingress.nginx.kubebuilder.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress.nginx.kubebuilder.io
  resources:
  - ingresses/status
  verbs:
  - get
