# permissions for end users to view ingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ingress-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ingress-nginx-kubebuilder
    app.kubernetes.io/part-of: ingress-nginx-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: ingress-viewer-role
rules:
- apiGroups:
  - ingress.nginx.kubebuilder.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingress.nginx.kubebuilder.io
  resources:
  - ingresses/status
  verbs:
  - get
